<?php

namespace AppBundle\Repository;

/**
 * CampagnGoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampagnGoalRepository extends \Doctrine\ORM\EntityRepository
{
}
