<?php

namespace AppBundle\Repository;

/**
 * CommunicationMediumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationMediumRepository extends \Doctrine\ORM\EntityRepository
{
}
