<?php

namespace AppBundle\Repository;

/**
 * ConfIdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfidRepository extends \Doctrine\ORM\EntityRepository
{
}
