<?php

namespace AppBundle\Repository;

/**
 * uBuilderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uBuilderRepository extends \Doctrine\ORM\EntityRepository
{
}
