<?php

namespace AppBundle\Repository;

/**
 * UrlAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlAdressRepository extends \Doctrine\ORM\EntityRepository
{
}
